name: 🧩 Feature
description: Create an issue based on a feature/topic
labels: [feature]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: false
      description: How urgent should this issue be solved?
      options:
        - 🟣 Lowest
        - 🔵 Low
        - 🟢 Medium (Default)
        - 🟡 High
        - 🟠 Highest
        - 🔴 Critical
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
