name: Create branch from issue

on:
  issues:
    types: [ opened ]

jobs:
  create-branch-from-issue:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log the issue number id
        run: echo ${{ github.event.issue.number }}
        
      - name: Create feature branch
        if: ${{ contains(github.event.issue.labels.*.name, 'feature') }}
        run: |
          git fetch
          git checkout develop
          git checkout -b feature/${{ github.event.issue.number }}
          git push --set-upstream origin feature/${{ github.event.issue.number }}
          
      - name: Create hotfix branch
        if: ${{ contains(github.event.issue.labels.*.name, 'hotfix') }}
        run: |
          git fetch
          git checkout main
          git checkout -b hotfix/${{ github.event.issue.number }}
          git push --set-upstream origin hotfix/${{ github.event.issue.number }}
