# This is a basic workflow to help you get started with Actions

name: Show issue created

# Controls when the workflow will run
on:
  issues:
    types: [ opened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run"
  run:
    if: ${{ contains(github.event.issue.labels.*.name, 'feature') }}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install git-flow tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-flow

      - name: Log the issue number id
        run: echo ${{ github.event.issue.number }}
        
      - name: Create feature branch
        run: git flow feature start feature_branch
